# Generated by Django 2.2 on 2019-04-08 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restuarants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restuarantlocation',
            name='category',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
