# Generated by Django 2.2 on 2019-04-09 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restuarants', '0003_auto_20190408_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='restuarantlocation',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
