# Generated by Django 2.2 on 2019-04-09 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restuarants', '0004_restuarantlocation_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restuarantlocation',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
