# Generated by Django 2.2 on 2019-04-10 10:00

from django.db import migrations, models
import restuarants.validators


class Migration(migrations.Migration):

    dependencies = [
        ('restuarants', '0005_auto_20190409_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restuarantlocation',
            name='category',
            field=models.CharField(max_length=120, null=True, validators=[restuarants.validators.validate_category]),
        ),
    ]
